### ISSUE TITLE
Value

### ISSUE THREAD

**Issue by q-learning-trader** [YC-Coder-Chen/GRU-stock-price-prediction#1]
I wonder to know what is the value of this?
You are trying to predict the lagged value in the past of stock price, which is given as input.
Why?

![image](https://user-images.githubusercontent.com/60422638/75603592-2b0a1580-5ad0-11ea-93ba-0077234d70a6.png)

**Comment by q-learning-trader** [comment]
@YC-Coder-Chen it does not predict anything, it only takes the last price value:

![image](https://user-images.githubusercontent.com/60422638/75606485-97474200-5aed-11ea-900d-f3fb121b75fe.png)

**Comment by YC-Coder-Chen** [comment]
Hi, thank you for your question. Firstly, the demo uses the previous stock price and other information to predict future 1-day stock price, there is no information leakage in it. Secondly, yes, it seems that what model predicts for the future 1-day stock price is very close to the previous stock price. I think the reason for this is that in our demo, the only valuable information for the stock price prediction is the previous stock price. And that is exactly what the model found. Actually I also tried a traditional GRU/LSTM model, and it worked much worse than this framework. You can try to apply this framework to dataset with a different time frame.
